Repository oSoc19/reliability-score-frontend, pull requests merged in 2019-07, with the labels that each got.

#7 CI deployment
  .travis-ci.yml
Labels: CI

#8 Ui representation
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/components/Animations.css
  src/components/DirectionChart.js
  src/components/DirectionCollection.js
  src/components/DirectionDetail.js
  src/components/DirectionForm.js
  src/components/DirectionItem.js
  src/components/DirectionStationDetail.js
  src/components/DotsTutorial.js
  src/components/DotsWidgetComponent.js
  src/components/Header.css
  src/components/Header.js
  src/components/HeaderBackButton.js
  src/components/HeaderDetail.js
  src/components/Layout.js
  src/components/PlannerPanel.css
  src/components/PlannerPanel.js
  src/components/SearchPanel.css
  src/components/SearchPanel.js
  src/components/StationItem.js
  src/components/chart-options.js
  src/fonts/icomoon/icomoon.eot
  src/fonts/icomoon/icomoon.svg
  src/fonts/icomoon/icomoon.ttf
  src/fonts/icomoon/icomoon.woff
  src/images/.DS_Store
  src/images/arrival.png
  src/images/calendar.png
  src/images/clock.png
  src/images/departure.png
  src/images/light-arrow-blue.png
  src/images/logo.png
  src/images/orange-warning.png
  src/images/white-warning.png
  src/index.css
  src/index.js
  src/serviceWorker.js
  yarn.lock
Labels: enhancement

#10 Ui representation
  package-lock.json
  package.json
  src/components/DirectionForm.js
  src/components/Header/Header.js
  src/components/Layout.js
  src/components/NoMoreResult.js
  src/components/PlannerPanel/Chart.css
  src/components/PlannerPanel/Chart.js
  src/components/PlannerPanel/Direction.css
  src/components/PlannerPanel/DirectionChart.js
  src/components/PlannerPanel/DirectionCollection.js
  src/components/PlannerPanel/DirectionItem.js
  src/components/PlannerPanel/DotsTutorial.js
  src/components/PlannerPanel/DotsWidget.js
  src/components/PlannerPanel/EarlierDirections.js
  src/components/PlannerPanel/LaterDirections.js
  src/components/PlannerPanel/LoadingDirectionsButtonHOC.js
  src/components/PlannerPanel/PlannerPanel.css
  src/components/PlannerPanel/PlannerPanel.js
  src/components/PlannerPanel/PreviousDirections.js
  src/components/PlannerPanel/StationItem.js
  src/components/PlannerPanel/ViaStationItem.js
  src/components/SearchPanel.css
  src/components/SearchPanel.js
  src/components/Util.js
  src/images/no-chart-data.png
  src/index.css
Labels: enhancement

#16 Footer send to backward - Temporary fix
  src/index.css
Labels: bug
